sudo: required
services:
  - docker

before_install:
  - docker build -t ile/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true ile/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-north-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-eu-north-1-268630953295"
  bucket_path: "docker-react"
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
  on:
    branch: main